### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by effectively0** [KiralyCraft/callrecorder-axet#6]
How is this installed exactly? Is not clear whether it needs to be a clean install or if the old Axet's needs to be uninstalled after installing this. 
Should I install Axet's apk (or zip file via Magisk) and then install your zip file via Magisk? 
I uninstalled Magisk's Axet and apk from https://github.com/di72nn/callrecorder-axet/releases and then installed this one from Magisk, but there is no UI app.

**Comment by KiralyCraft** [comment]
Thanks for the heads up, it's indeed not clear enough - I'll update the readme soon. You should uninstall the old version of Axet, the one installed normally, and then just flash this through Magisk. If it all goes well, it should say "All done, please reboot" at the end. I haven't tested many Android versions, since I'm still on Pie. There's still an uncertain confirmation it works on Android 11: https://github.com/KiralyCraft/callrecorder-axet/issues/3#issuecomment-774657888

**Comment by effectively0** [comment]
Thanks for the prompt response. I asked a silly sounding question since this Magisk module alone does not yield any UI app and neither does it seem to fix the silent recordings in the other versions of the Axet app.
Must be because of this Android 12 device.

**Comment by KiralyCraft** [comment]
I see, maybe things have changed from Android 9 to 12 sufficient enough to break things. Doesn't it show even after a reboot? Right after installing it should indeed not show, and requires a reboot to do so. The module alone installs version 1.7.13 (which is quite old at this point, I have to admit), so it should definitely show *something*. 

If you want to embed a new version, the procedure is quite simple: 
- Download the module as a zip, extract it somewhere
- Replace common/com.github.axet.callrecorder_219.apk with a newer version, give it any name
- Replace all 3 references to "com.github.axet.callrecorder_219.apk" from "install.sh" to the new name (edit with notepad)
- Re-zip the module
- Done, flash

I'll be getting a new device soon, and it's very likely it'll run Android 12. When it inevitably happens, I'll take a look at this, since otherwise, I have no other device capable of running it.

**Comment by effectively0** [comment]
It shows nothing in the app drawer even upon reboot despite showing the module as installed and enabled within Magisk Manager.

I was about to try your above suggestion, but I found that someone called Lavmint posted a working Magisk Module on Axet's gitlab issue #201 using 1.8.2. 

Out of curiosity, do you know if Axet's gitlab would have implemented your fix or an alternate method? I'm a bit confused as the Axet's gitlab has releases from a few months ago (albeit with many issue reports), but the last release here was over a year ago. Hard for a layman like myself to keep track of the various forks and causes of different issues.
Thanks for all your help.

**Comment by KiralyCraft** [comment]
It looks like di72nn's approach (the one who owns the other repo, pointed in the comments of issue #201) follows a more standard approach, more close to Magisk's guidelines, which may be the reason why my version broke. If that works for you, I highly recommend you stick with that and update it regularly through F-Droid; I'll also point it in the readme here.

Axet's GitLab has more recent releases because of him releasing the actual recorder itself, while the Magisk module is old because it doesn't need updating - but the app included within does. Luckily, once installed, it can simply be updated as usual.

This fix is unlikely to be implemented at Axet's, because of a few reasons:

- I doubt he wants to support a Magisk module on top of the application itself
- The reason for which these modules exist in the first place is not a fault of Axet's, but a limitation imposed by Android by which only "System" applications can record the output of calls. This makes sense from a security standpoint, but it brings up issues when we legitimately want to do this. 

So whichever method works, stick with that. Many thanks for the debugging!
